---
- name: Setup Jenkins with Java and Docker on t2.micro (with memory limit)
  hosts: jenkins_node
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - openjdk-11-jdk
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
          - wget
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
        filename: docker

    - name: Update apt cache after Docker repo
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add Jenkins GPG key (manual command)
      shell: |
        wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | apt-key add -

    - name: Add Jenkins repository
      shell: |
        echo deb https://pkg.jenkins.io/debian binary/ > /etc/apt/sources.list.d/jenkins.list

    - name: Update apt cache after Jenkins repo
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Add jenkins user to docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Set Java memory limits for Jenkins
      lineinfile:
        path: /etc/default/jenkins
        regexp: '^JAVA_ARGS='
        line: 'JAVA_ARGS="-Xmx512m -Djava.awt.headless=true"'
      notify: Restart Jenkins

  handlers:
    - name: Restart Jenkins
      systemd:
        name: jenkins
        state: restarted
        enabled: yes
